### ISSUE TITLE
Unable to build on virtualbox

### ISSUE THREAD

**Issue by mmatongo** [kisslinux/kiss#122] opened 2020-03-11 16:35 UTC
I've been trying to build KISS on a virtual machine without any success, I keep getting the same error on multiple machines running different operating systems. I wanted to find out if this was a vbox specific problem?

![VirtualBox_ll_09_03_2020_10_48_02](https://user-images.githubusercontent.com/40806126/76441075-c6e02f00-63b6-11ea-9e0d-11fdd4900b5e.png)

This happens irrespective of what command is run.

**Comment by dylanaraps** [comment] 2020-03-11 16:38
Your image link doesn't load for me!

**Comment by mmatongo** [comment] 2020-03-11 16:40
> Your image link doesn't load for me!

Fixed it. 
By any command, I mean any build commands. i.e
`kiss build   gnupg1 `

**Comment by dylanaraps** [comment] 2020-03-11 16:43
That's a network issue though I can't reproduce it for the same URL. I assume you have working internet in the virtual machine?

**Comment by dylanaraps** [comment] 2020-03-11 16:43
Does: `wget https://ftp.gnu.org/gnu/binutils/binutils-2.34.tar.xz` work?

**Comment by mmatongo** [comment] 2020-03-11 16:50
![VirtualBox_Linux _11_03_2020_18_46_33](https://user-images.githubusercontent.com/40806126/76442120-589c6c00-63b8-11ea-8a29-38e22981142e.png)
No, that's the response I get, I've tried different links.

**Comment by dylanaraps** [comment] 2020-03-11 16:51
Yes. You don't have working network. ie, there's no internet in your virtual machine. This isn't a bug so I'm going to close this. Check your kernel drivers, check your kernel config and check your virtualbox settings.

If you require further help, ask around in `#kisslinux` on Freenode.net

**Comment by konimex** [comment] 2020-03-11 16:52
I'd suggest you copy `/etc/resolv.conf` from your OS to the chroot.

**Closed by dylanaraps** 2020-03-11 16:51 UTC

**Comment by mmatongo** [comment] 2020-03-11 17:00
> I'd suggest you copy `/etc/resolv.conf` from your VBox OS to the chroot.

This worked beautifully.
Thank you @konimex and @dylanaraps
