### ISSUE TITLE
Feature request: "--keep-going"

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/kiss#92] opened 2020-01-27 05:00 UTC
When I type "kiss b" or "kiss b foo bar" I want the option to keep going when a build fails, attempting to build as many things as possible, and at the end 1. offer to install the packages that did build (as normal) and 2. to display which packages failed, if any did fail. Gentoo's emerge has this option and it is quite handy. Thanks

**Comment by dylanaraps** [comment] 2020-01-27 23:01
The only issue is that we shouldn't ignore failures for builds which will be installed immediately as dependencies. This should be easy to add for every other case though.

**Comment by a-schaefers** [comment] 2020-01-28 04:24
While we're at it, something to consider while implementing this feature might be to save [all] the output somewhere in a kiss.log file, or does kiss already do this and I haven't noticed?

**Comment by dylanaraps** [comment] 2020-01-28 07:18
I've tried doing this. 

The issue is that you can't reliably store logs while retaining the exit status of the build script or breaking `>/dev/null` etc.

**Comment by dylanaraps** [comment] 2020-01-28 08:19
Logs are done: https://github.com/kisslinux/kiss/commit/60ac1c094e68214f93d756446ff67ee6109ff793

See how it's implemented... lol

**Comment by dylanaraps** [comment] 2020-02-04 11:18
I don't think this makes sense to add as a feature.

1) If a build fails, it is a bug or OOM.
2) We don't use command-line arguments.
3) This can already be done with a simple for loop or script.

Simple loop:

```sh
for pkg in pkg1 pkg2 pkg3; do kiss b "$pkg"; done
```

Script (All features):

```sh
set -f 

for pkg in pkg1 pkg2 pkg3; do
    if kiss b "$pkg"; then
        done="$done $pkg"
    else
        fail="$fail $pkg"
    fi
done

[ "$fail" ] && {
    printf '%s\n' "The following packages failed to build: $fail"
}

[ "$done" ] && {
    printf '%s' "Install built packages? ($done)"
    read -r && kiss i $done
}    
```

**Closed by dylanaraps** 2020-02-04 11:18 UTC
Labels: enhancement
