### ISSUE TITLE
kiss doesn't detect file conflicts between packages

### ISSUE THREAD

**Issue by konimex** [kisslinux/kiss#71] opened 2019-11-19 00:25 UTC
## Issue

Self-explanatory. In my case, the package involved is `clang` and my own `llvm-unified` trial package.

## How to reproduce

While my `llvm-unified` is installed, install `clang`. It doesn't warn of conflicts, but it does warn of `llvm` not being installed, which means the first check fails to do its job.

My `llvm-unified` build script is available upon request.

[Build log](http://0x0.st/z6Jy.log)

[KISS `clang` manifest](https://0x0.st/z6Jv.txt)  
[My `llvm-unified` manifest](https://0x0.st/z6Jw.txt)

**Comment by scsijon** [comment] 2019-11-19 01:03
On 19/11/19 11:25, M. Herdiansyah wrote:
> ## Issue
> 
> Self-explanatory. In my case, the package involved is `clang` and my own `llvm-unified` trial package.
> 
> ## How to reproduce
> 
> While my `llvm-unified` is installed, install `clang`. It doesn't warn of conflicts, but it does warn of `llvm` not being installed, which means the first check fails to do its job.
> 
> My `llvm-unified` build script is available upon request.
> 
> [Build log](http://0x0.st/z6Jy.log)
> 
> [KISS `clang` manifest](https://0x0.st/z6Jv.txt)
> [My `llvm-unified` manifest](https://0x0.st/z6Jw.txt)
> 
  Go here >
http://llvm.org/docs/GettingStarted.html
It should help you, especially  the "Clang getting started" link.

Personally, I downloaded a prebuilt llvm/clang from their site and built 
both as separate packages using it via chroot as had been sugested 
elsewhere, and that worked, but not in KISS. I'm still 'reading' through 
the KISS system to gather enough knowledge before I start, as I come 
from a different linux background.

**Comment by konimex** [comment] 2019-11-19 01:19
I honestly don't understand what you meant. I've successfully built the package, it's just when I install it, it somehow is successful when it *shouldn't* be.

**Comment by dylanaraps** [comment] 2019-11-19 06:15
It's finding a conflict with `clang` but it isn't aborting there. Need to investigate further.

```sh
+ grep -svFxf /var/db/kiss/installed/clang/manifest -
+ '[' -f //var/db/kiss/installed/clang/version ]
+ read -r file
+ '[' -f //var/db/kiss/installed/clang/sources ]
+ read -r file
+ '[' -f //var/db/kiss/installed/clang/patches/cfe-004-add-musl-triples.patch ]
+ read -r file
+ '[' -f //var/db/kiss/installed/clang/patches/cfe-003-fix-unwind-chain-inclusion.patch ]
+ read -r file
+ '[' -f //var/db/kiss/installed/clang/patches/ ]
+ read -r file
+ '[' -f //var/db/kiss/installed/clang/manifest ]
+ read -r file
+ '[' -f //var/db/kiss/installed/clang/depends ]
+ read -r file
+ '[' -f //var/db/kiss/installed/clang/checksums ]
+ read -r file
+ '[' -f //var/db/kiss/installed/clang/build ]
+ read -r file
+ '[' -f //var/db/kiss/installed/clang/ ]
+ read -r file
+ '[' -f //var/db/kiss/installed/ ]
+ read -r file
+ '[' -f //var/db/kiss/ ]
+ read -r file
+ '[' -f //var/db/ ]
+ read -r file
+ '[' -f //var/ ]
+ read -r file
+ '[' -f //usr/share/scan-view/startfile.py ]
+ printf '%s\n' /usr/share/scan-view/startfile.py
+ '[' -s /home/koni/.cache/kiss/8249-m ]
```

**Comment by scsijon** [comment] 2019-11-19 09:40
cmake version 3.4.3 or later?

cmake set to build with>  cmake -C <path to cache file> <path to sources>

Variables customize how the build will be generated. Options are boolean 
variables, with possible values ON/OFF. Options and variables are 
defined on the CMake command line like this:

$ cmake -DVARIABLE=value path/to/llvm/source

You can set a variable after the initial CMake invocation to change its 
value. You can also undefine a variable:

$ cmake -UVARIABLE path/to/llvm/source

Variables are stored in the CMake cache. This is a file named 
CMakeCache.txt stored at the root of your build directory that is 
generated by cmake. Editing it yourself is not recommended.

Variables are listed in the CMake cache and later in this document with 
the variable name and type separated by a colon. You can also specify 
the variable and type on the CMake command line:

$ cmake -DVARIABLE:TYPE=value path/to/llvm/source

?shared or static libs in your system, llvm by default looks for static,
BUILD_SHARED_LIBS=on for shared

and that's just for llvm part.

http://clang.llvm.org/get_started.html should give you a good basics for 
clang

Looking at your file online, it's clear to me that it can't find the 
paths to the llvm libs and source code (post build), you do still have 
them of course and still in the same place llvm had them in when built, 
they wern't deleted after llvm was built were they, it needs them to 
build clang properly.

I'll print it out and look into it further in a day or two after doing 
some checking in my own build notes if needed still. I built all the 
packages together and they were ok afterwards, maybe some things gone 
awry building in start-stop-start stages.

-------------------------------
On 19/11/19 17:15, dylan wrote:
> It's finding a conflict with `clang` but it isn't aborting there. Need to investigate further.
> 
> ```sh
/cut

**Comment by scsijon** [comment] 2019-11-19 09:55
and if you still have your llvm log i'd like to see that also.

**Comment by dylanaraps** [comment] 2019-11-19 15:29
I can't seem to reproduce this:

```sh
-> kiss i zlib
Password:
-> zlib Checking for package conflicts
/var/db/kiss/installed/busybox/manifest:/usr/bin/ls
!> Package 'zlib' conflicts with another package
```

(Made `zlib` install a file as `/usr/bin/ls` to test.)

**Comment by dylanaraps** [comment] 2019-11-19 15:33
Here's what a working log looks like: https://gist.github.com/dylanaraps/be607129692e10cbd377c27824883f7b

**Comment by dylanaraps** [comment] 2019-11-19 15:43
It looks like this check (`+ '[' -s /home/koni/.cache/kiss/8249-m ]`) is returning `1` (False) for some reason.

Try changing the code to this:

```sh
    # Filter the existing file list through the manifest of the
    # presently installed version of the package (if it exists).
    grep -svFxf "$sys_db/$2/manifest" - 2>/dev/null > "$cac_dir/$pid-m"
    vim "$cac_dir/$pid-m"
```

It'll open `vim` with the the filtered manifest from the tarball. This is what the code uses to check for conflicts against the system.

**Comment by konimex** [comment] 2019-11-19 20:54
The filtered list is an empty file on my end.

**Comment by konimex** [comment] 2019-11-20 08:29
Test builds for package Dummies [A](https://github.com/konimex/kiss-personal/tree/master/dummy-a) and [B](https://github.com/konimex/kiss-personal/tree/master/dummy-b). See if you can reproduce it.

[Log for dummy A, installed first](https://0x0.st/z6Ef.log)  
[Log for dummy B, installed second](https://0x0.st/z6EO.log)

[Manifest for dummy A](https://0x0.st/z6EV.txt)  
Manifest for dummy B: Look at manifest for dummy A. Difference only in the package name.

**Comment by dylanaraps** [comment] 2019-11-20 12:28
Try the latest master.

**Comment by konimex** [comment] 2019-11-20 12:41
Doesn't seem to work.

[Log for dummy A, installed first](https://0x0.st/z661.log)  
[Log for dummy B, installed second](https://0x0.st/z66j.log)

**Comment by dylanaraps** [comment] 2019-11-20 22:47
Try master again. :+1:

**Comment by konimex** [comment] 2019-11-20 23:45
Nope. Doesn't work either.

[Dummy B, installed first](https://0x0.st/z6DP.log)  
[Dummy A, installed second](https://0x0.st/z6DZ.log)

**Comment by dylanaraps** [comment] 2020-01-06 05:55
Should be fixed in: https://github.com/kisslinux/kiss/commit/c8a29c451eb774350c1e143be5cbb019b84a2bd7

**Closed** 2020-01-06 05:58 UTC
Labels: bug, can't reproduce
